# Example Plugin Properties File

# Plugin Name
name=ExamplePlugin

# Plugin Version
version=1.0

# Plugin UUID (used for persistent data storage) [Generator](https://www.uuidgenerator.net/version4)
uuid=d152236f-96df-4be1-8f2b-6738c4194ed7

# Plugin Main Class
main=cloud.thehsi.ExamplePlugin.Main

# Plugin's target API version (0.0.8/0.0.8-0.0.9)
api-target=0.0.9